name: ecommerce_app
description: An Ecommerce App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.0
  get_it: ^7.6.4
  go_router: ^13.0.1
  hive: ^2.2.3
  http_interceptor: ^1.0.2
  intl: ^0.18.0
  path_provider: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.6
  test: ^1.19.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
